#!/usr/bin/env python3
"""Generate the TitanOS logo assets from the kit spec.

The kit HTML said "files delivered alongside" but only the HTML arrived, so the assets are generated
here from the same numbers. Everything is derived from docs/brand_kit.py, so the marks cannot drift
from the palette the documents use.

WHAT COMES OUT
    TitanOS_Logo_Primary.svg    navy + gold, transparent   — light backgrounds
    TitanOS_Logo_Reversed.svg   white + gold, transparent  — the brand navy or darker
    TitanOS_Logo_Primary.png    same, 4x (2800 x 880)
    TitanOS_Logo_Reversed.png   same, 4x, on transparent

THE FONT CAVEAT, AGAIN, BECAUSE IT AFFECTS WHICH FILE TO USE WHERE
The SVGs declare `Georgia, 'Times New Roman', serif` and will render in Georgia on any Mac or
Windows machine — use them for decks, docs and web. The PNGs are rasterised here on Linux, where
Georgia does not exist, so they come out in Times. If a PNG has to match the SVG exactly, regenerate
it on a machine that has Georgia; the SVG is the master.

Usage:
  python3 docs/build_logo_assets.py [outdir]
"""

import argparse
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from reportlab.lib.colors import HexColor      # noqa: E402
from reportlab.pdfgen import canvas            # noqa: E402

import brand_kit as BK                         # noqa: E402

VB_W, VB_H = BK.LOCKUP["vb_w"], BK.LOCKUP["vb_h"]
L = BK.LOCKUP


def svg(reversed_=False):
    """The lockup as SVG. Structure and numbers are the kit's; only the colours differ by variant."""
    wordmark = BK.WHITE if reversed_ else BK.NAVY
    tagline = BK.MIST if reversed_ else BK.SLATE
    variant = "Reversed" if reversed_ else "Primary"
    note = ("For the brand navy or darker backgrounds only — white and gold will not read on light."
            if reversed_ else "For light backgrounds.")
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- TitanOS logo, {variant.lower()} lockup. {note}
     Generated by docs/build_logo_assets.py from docs/brand_kit.py — regenerate, do not hand-edit.
     Georgia is the specified wordmark face, with Times New Roman as the substitute where Georgia
     is unavailable (notably Linux and server-side PDF rendering). -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {VB_W:.0f} {VB_H:.0f}"
     width="{VB_W:.0f}" height="{VB_H:.0f}" role="img"
     aria-label="TitanOS — {BK.BRAND['tagline'].title()}">
  <title>TitanOS — {BK.BRAND['tagline'].title()}</title>
  <text x="{VB_W/2:.0f}" y="{L['wordmark_baseline']:.0f}" text-anchor="middle"
        font-family="Georgia, 'Times New Roman', serif" font-weight="bold"
        font-size="{L['wordmark_size']:.0f}" letter-spacing="{L['wordmark_track']:.0f}">
    <tspan fill="{wordmark}">{BK.BRAND['wordmark_dark']}</tspan><tspan fill="{BK.GOLD}">{BK.BRAND['wordmark_accent']}</tspan>
  </text>
  <line x1="{L['rule_x0']:.0f}" y1="{L['rule_y']:.0f}" x2="{L['rule_x1']:.0f}" y2="{L['rule_y']:.0f}"
        stroke="{BK.GOLD}" stroke-width="{L['rule_w']:.0f}"/>
  <text x="{VB_W/2:.0f}" y="{L['tagline_baseline']:.0f}" text-anchor="middle"
        font-family="Arial, Helvetica, sans-serif" font-weight="bold"
        font-size="{L['tagline_size']:.0f}" letter-spacing="{L['tagline_track']}"
        fill="{tagline}">{BK.BRAND['tagline']}</text>
</svg>
'''


def png(path, reversed_=False, scale=4):
    """Rasterise via a one-page PDF at 4x and pdftoppm, keeping the background transparent."""
    pdf = path + ".tmp.pdf"
    # The page is the viewBox at 1:1 in POINTS; `scale` is applied once, by the rasteriser's DPI.
    # Scaling the page as well as the DPI is how the first run produced 11200x3520 instead of the
    # 2800x880 the kit promises — 16x, not 4x. Vector art, so it looked fine and was simply wrong.
    w, h = VB_W, VB_H
    c = canvas.Canvas(pdf, pagesize=(w, h))
    # No background rectangle at all — pdftoppm -alpha then gives a transparent PNG, which is what
    # a logo asset has to be. Drawing a white box here would quietly ruin it for dark decks.
    BK.draw_lockup(c, w / 2, h, w, reversed_=reversed_)
    c.showPage()
    c.save()

    out_root = path[:-4] if path.endswith(".png") else path
    # pdftocairo, not pdftoppm. This poppler build's pdftoppm has no -alpha flag at all (it exits 99),
    # and a logo asset without transparency is not a logo asset — the reversed mark in particular
    # would arrive as white text on an opaque white block. pdftocairo -transp does it properly.
    subprocess.run(["pdftocairo", "-png", "-transp", "-r", str(72 * scale),
                    "-singlefile", pdf, out_root], check=True, capture_output=True)
    os.remove(pdf)
    return path


# THE KIT HAS NO STANDALONE MARK, SO THIS ONE IS DERIVED.
#
# The kit delivers two lockups and nothing for a favicon, an avatar or the collapsed sidebar — all
# of which the product needs and already had. Rather than leave the old off-palette mark in place,
# it is rebuilt here in the new navy and gold, keeping the previous structure (rounded navy square,
# gold T, small OS). Derived, not kit-canonical, and labelled as such on the brand sheet so nobody
# cites it as spec.
def mark_png(path, size=512):
    pdf = path + ".tmp.pdf"
    c = canvas.Canvas(pdf, pagesize=(size, size))
    c.setFillColor(HexColor(BK.NAVY))
    c.roundRect(0, 0, size, size, size * 0.18, stroke=0, fill=1)
    c.setFont(BK.PDF_SERIF, size * 0.52)
    c.setFillColor(HexColor(BK.GOLD))
    t = "T"
    c.drawString((size - c.stringWidth(t, BK.PDF_SERIF, size * 0.52)) / 2, size * 0.40, t)
    c.setFont(BK.PDF_SANS, size * 0.13)
    c.setFillColor(HexColor(BK.MIST))
    os_ = "OS"
    c.drawString((size - c.stringWidth(os_, BK.PDF_SANS, size * 0.13)) / 2, size * 0.20, os_)
    c.showPage()
    c.save()
    root = path[:-4]
    subprocess.run(["pdftocairo", "-png", "-r", "72", "-singlefile", pdf, root],
                   check=True, capture_output=True)
    os.remove(pdf)
    return path


def main(outdir):
    os.makedirs(outdir, exist_ok=True)
    written = []
    for reversed_, name in [(False, "TitanOS_Logo_Primary"), (True, "TitanOS_Logo_Reversed")]:
        p = os.path.join(outdir, name + ".svg")
        with open(p, "w") as f:
            f.write(svg(reversed_))
        written.append(p)
        written.append(png(os.path.join(outdir, name + ".png"), reversed_=reversed_))

    written.append(mark_png(os.path.join(outdir, "TitanOS_Mark.png")))

    # Legacy filenames, regenerated from the new kit rather than left behind. App.jsx falls back to
    # /titanos-logo-full.png and /titanos-mark.png, and build_brand_sheet.py loads all three by
    # name; leaving the old files in place would have shipped the previous palette everywhere those
    # paths are used, which is exactly the kind of half-applied rebrand nobody notices for a month.
    for legacy, src_reversed in [("titanos-logo-full.png", False),
                                 ("titanos-logo-knockout.png", True)]:
        written.append(png(os.path.join(outdir, legacy), reversed_=src_reversed))
    written.append(mark_png(os.path.join(outdir, "titanos-mark.png")))

    for p in written:
        print(f"  {os.path.getsize(p):>8,} B  {os.path.relpath(p)}")
    print(f"\ntagline: {BK.BRAND['tagline']}")
    print(f"navy {BK.NAVY} · gold {BK.GOLD} · slate {BK.SLATE} · mist {BK.MIST}")
    print(f"gold on white measures {BK.GOLD_ON_WHITE:.2f}:1 — accent only, never body text")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("outdir", nargs="?",
                    default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "brand"))
    main(ap.parse_args().outdir)
